CREATE DATABASE customer_db;
USE customer_db;
select * from customer_data;

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer_data
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount 
from customer_data
where discount_applied='yes' and purchase_amount>= (select avg(purchase_amount) from customer_data);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, avg(review_rating) as "Average Product Rating"
from customer_data
group by item_purchased
order by avg(review_rating) desc
limit 5;

use customer_db;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,
       AVG(purchase_amount) AS avg_purchase
FROM customer_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS avg_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_data
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
	   round(sum(case 
                 when discount_applied = 'yes' then 1
                 else 0
                 end) / count(*) *100,2)as discount_rate
from customer_data
group by item_purchased
order by discount_rate desc
limit 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id ,previous_purchases,
case 
   when previous_purchases = 1 then 'New'
   when previous_purchases between 2 and 10 then 'Returning'
   else 'Loyal'
   End as customer_segment
from customer_data
)
select customer_segment, count(*) as 'Number of Customers'
from customer_type
group by customer_segment;   


-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
Row_Number() over (partition by category order by count(customer_id) DESC) as item_rank
from customer_data
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank<=3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
 count(customer_id)  as repeat_buyers
 from customer_data
 where previous_purchases >5
 group by subscription_status;
 

-- Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer_data
group by age_group
order by total_revenue desc;






